Add a root parameter to cmdline when there's no initramfs
Normally we would put a configuration file into the initramfs, but
custom kernels may boot without initramfs, so it's useless for them. We
still need to specify a root for them, so put it in the cmdline.

Functions are from my flash-kernel merge request, with small changes.
Also, uses findmnt instead of reading /etc/fstab directly.

Signed-off-by: Alper Nebi Yasak <alpernebiyasak@gmail.com>

diff --git a/update-depthcharge b/update-depthcharge
--- a/update-depthcharge
+++ b/update-depthcharge
@@ -98,7 +98,7 @@ DTB_NAME="$(get_config dtb-name)" || :
 MAX_SIZE="$(get_config max-size)" || :
 
 # Load user configuration.
-CMDLINE="$(get_config cmdline)" || :
+CMDLINE_USER="$(get_config cmdline)" || :
 COMPRESS="$(get_config compress)" || :
 DESCRIPTION_FMT="$(get_config description)" || :
 
@@ -117,12 +117,35 @@ generate_image() {
 
     INITRAMFS="/boot/initrd.img-${kversion}"
     if [ ! -r "$INITRAMFS" ]; then
-        error "No initramfs found for kernel version '${kversion}'."
+        warn "No initramfs found for kernel version '${kversion}'."
+        INITRAMFS=""
     fi
 
     DTBS="$(find "/usr/lib/linux-image-${kversion}" -name "$DTB_NAME")"
     if [ -z "$DTBS" ]; then
         error "No dtb file '$DTB_NAME' found for version '$kversion'."
+    fi
+
+    CMDLINE="${CMDLINE_USER}"
+    # Custom kernels might still be able to boot without an initramfs,
+    # but we need to inject a root= parameter for that.
+    if [ -z "$INITRAMFS" ]; then
+        info "Booting without an initramfs requires a root parameter" \
+            "in the kernel cmdline."
+        case "$CMDLINE_USER" in
+            # Skip if the user specified a root=* in cmdline.
+            *root=*)
+                info "Keeping root parameter as in user configured cmdline."
+                ;;
+            *)
+                rootcmd="$(get_root_cmdline)" \
+                    || error "Couldn't figure out a root cmdline parameter."
+                check_root_cmdline "$rootcmd" \
+                    || error "An initramfs is required for '$rootcmd'."
+                info "Prepending '$rootcmd' to the kernel cmdline."
+                CMDLINE="$rootcmd $CMDLINE"
+                ;;
+        esac
     fi
 
     # We must do this here and not outside with others since --all
