Add a --no-write option to disable writing to disk
Signed-off-by: Alper Nebi Yasak <alpernebiyasak@gmail.com>

diff --git a/update-depthcharge b/update-depthcharge
--- a/update-depthcharge
+++ b/update-depthcharge
@@ -9,12 +9,14 @@ mkdir -p "$CACHE"
 
 print_help() {
 cat <<EOF
-Usage: update-depthcharge [-k VERSION]
+Usage: update-depthcharge [options]
 
 Options:
  -h, --help              Show this help message.
+ -a, --all               Rebuild depthcharge images for all versions.
  -k, --kversion VERSION  Use a specific kernel version instead of the
                          latest version.
+ -n, --no-write          Don't write the image to disk.
 EOF
 }
 
@@ -27,6 +29,14 @@ while [ "$#" -gt 0 ]; do
         -k|--kversion)
             KVERSION="$2"
             shift 2
+            ;;
+        -a|--all)
+            ALL_IMAGES=yes
+            shift 1
+            ;;
+        -n|--no-write)
+            NO_WRITE=yes
+            shift 1
             ;;
         --)
             shift
@@ -165,5 +175,22 @@ write_image() {
         || error "Failed to prioritize partition '$target'."
 }
 
-generate_image "$KVERSION"
-write_image "$KVERSION"
+if [ "$ALL_IMAGES" = yes ]; then
+    for v in $(linux-version list | linux-version sort); do
+        if generate_image "$v"; then
+            continue
+        elif [ "$v" = "$KVERSION" ]; then
+            error "Couldn't generate image for chosen version '$v'."
+        else
+            warn "Couldn't generate image for version '$v', ignoring."
+        fi
+    done
+else
+    generate_image "$KVERSION" \
+        || error "Couldn't generate image for chosen version '$v'."
+fi
+
+if [ "$NO_WRITE" != yes ]; then
+    write_image "$KVERSION" \
+        || error "Couldn't write image to disk for chosen version '$v'."
+fi
